[package]
name = "bean"
version = "0.1.0"
authors = ["Skyler Lipthay <sl@skylerlipthay.com>"]
edition = "2018"

[dependencies]
gc = "0.3"
gc_derive = "0.3"

[dev-dependencies]
ansi_term = "0.11"
rustyline = "1.0"
