[package]
name = "bean"
version = "0.1.0"
authors = ["Skyler Lipthay <sl@skylerlipthay.com>"]
edition = "2018"

[dependencies]
bacon_rajan_cc = "0.2"

[dev-dependencies]
ansi_term = "0.11"
rustyline = "1.0"
